version: "3"

services:

    #==================== OpenCBR Instances ====================

    #===== Instance 1
    opencbr-mysql-1:
        image: mysql/mysql-server:5.6
        env_file:
            - opencbr/db.env
        volumes:
            - ./opencbr/openmrs_db.sql:/docker-entrypoint-initdb.d/openmrs_db.sql
            - ./opencbr/openmrs_db_config-1.sql:/docker-entrypoint-initdb.d/openmrs_db_config.sql

    opencbr-openmrs-1:
        image: tomcat:7-jre7-alpine
        depends_on:
            - opencbr-mysql-1
        volumes:
            - ./opencbr/setenv.sh:/usr/local/tomcat/bin/setenv.sh
            - ./opencbr/openmrs.war:/usr/local/tomcat/webapps/openmrs.war
            - ./opencbr/openmrs-runtime-1.properties:/root/.OpenMRS/openmrs-runtime.properties
            - ./opencbr/modules:/root/.OpenMRS/modules
        ports:
            - "8080:8080"

    #===== Instance 2
    opencbr-mysql-2:
        image: mysql/mysql-server:5.6
        env_file:
            - opencbr/db.env
        volumes:
            - ./opencbr/openmrs_db.sql:/docker-entrypoint-initdb.d/openmrs_db.sql
            - ./opencbr/openmrs_db_config-2.sql:/docker-entrypoint-initdb.d/openmrs_db_config.sql

    opencbr-openmrs-2:
        image: tomcat:7-jre7-alpine
        depends_on:
            - opencbr-mysql-2
        volumes:
            - ./opencbr/setenv.sh:/usr/local/tomcat/bin/setenv.sh
            - ./opencbr/openmrs.war:/usr/local/tomcat/webapps/openmrs.war
            - ./opencbr/openmrs-runtime-2.properties:/root/.OpenMRS/openmrs-runtime.properties
            - ./opencbr/modules:/root/.OpenMRS/modules
        ports:
            - "8081:8080"


    #==================== OpenHIM and the XDS mediator ==================
    mongo:
        image: mongo:3.4
        volumes:
            - ./openhim/openhim_db.gz:/openhim_db.gz
            - ./openhim/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
        logging:
            driver: none

    openhim-core:
        image: wluyima/openhim-core
        env_file:
            - openhim/db.env
        volumes:
            - ./openhim/core-config.json:/usr/src/app/config/default.json
            - ./openhim/xds-mediator.properties:/usr/src/app/mediator/xds-mediator.properties
        ports:
            - "5000:5000"
            - "5001:5001"
            - "5002:5002"
            - "5050:5050"
            - "5051:5051"
            - "5053:5053"
            - "7788:7788"
        depends_on:
            - mongo

    openhim-console:
        image: jembi/openhim-console
        ports:
            - "80:80"
        volumes:
            - ./openhim/console-config.json:/usr/share/nginx/html/config/default.json
        depends_on:
            - openhim-core


    #==================== OpenEMPI ==================
    openempi-postgres:
        image: postgres:9.6
        env_file:
            - openempi/db.env

    openempi:
        image: wluyima/openempi
        env_file:
            - openempi/db.env
        volumes:
            - ./openempi/configure_db.sql:/usr/share/openempi/configure_db.sql
            - ./openempi/mpi-config.xml:/usr/share/openempi/openempi-entity-3.4.0c/conf/mpi-config.xml
        ports:
            - "8082:8080"
            - "3600:3600"
        stdin_open: true
        tty: true


    #==================== OpenSHR ==================
    openshr-mysql:
        image: mysql/mysql-server:5.6
        env_file:
            - openshr/db.env
        volumes:
            - ./openshr/openmrs_db.sql:/docker-entrypoint-initdb.d/openmrs_db.sql
            - ./openshr/openmrs_db_config.sql:/docker-entrypoint-initdb.d/openmrs_db_config.sql
          
    postgresql-openxds:
        image: postgres:9.6

    openshr-openmrs:
        image: tomcat:7.0-jre7-alpine
        depends_on:
            - openshr-mysql
        volumes:
            - ./openshr/openmrs.war:/usr/local/tomcat/webapps/openmrs.war
            - ./openshr/openmrs-runtime.properties:/root/.OpenMRS/openmrs-runtime.properties
            - ./openshr/modules:/root/.OpenMRS/modules
        ports:
            - "8083:8080"
            
    openshr-openxds:
        image: uwitech/openxds
        volumes:
            - ./openshr/XdsCodes.xml:/opt/openxds/conf/actors/XdsCodes.xml
        ports:
            - "8010:8010"
            - "8020:8020"
        depends_on:
            - postgresql-openxds


    #==================== DHIS2 ==================
    dhis2-postgres:
        image: postgres:9.6
        env_file:
            - dhis2/db.env
        volumes:
            - ./dhis2/database_schema.sql:/docker-entrypoint-initdb.d/database_schema.sql
            - ./dhis2/db_data.sql:/docker-entrypoint-initdb.d/db_data.sql

    dhis2:
        image: dhis2/dhis2-web:2.29-tomcat7-jre8-latest
        env_file:
            - dhis2/db.env
        volumes:
            - ./dhis2/dhis.conf:/usr/share/dhis2/dhis.conf
            - ./dhis2/setenv.sh:/usr/local/tomcat/bin/setenv.sh
            - ./dhis2/server.xml:/usr/local/tomcat/conf/server.xml
        ports:
            - "8084:8080"
        depends_on:
            - dhis2-postgres
